from Core.model_router import generate_response
from Core.comparator import prepare_comparison_input

async def compare_responses(responses: dict, evaluator_model="gemini") -> str:
    """
    Use an LLM to compare responses generated by different models.
    """
    formatted_responses = prepare_comparison_input(responses)

    prompt = f"""
    You are an expert AI evaluator. 
    Compare the following responses generated 
    by different models and determine which one is better based on 
    relevance, 
    coherence, and 
    informativeness. 
    Provide a detailed explanation for your choice.\n\n{formatted_responses}\n\n
    Please provide your evaluation in the following format:\n\n1. 
    Best Model: [Model Name]\n2. 
    Explanation: [Detailed explanation of why this model's response is better than the others]"""

    result = await generate_response(evaluator_model, prompt)
    return result